name: Building recovery

on:
  workflow_dispatch:

env:
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-10.0-deprecated
  DEVICE: r7
  DT_LINK: https://github.com/bavalucket/android_device_samsung_r7
  DT_PATH: device/samsung/r7
  TARGET: recoveryimage
  TZ: Asia/Manila

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
         # i love open source projects lmao
       - name: Initializing environment
         run: |
            git config --global user.name "bavalucket"
            git config --global user.email "americanking073@gmail.com"
            sudo -E apt-get clean
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python3 gcc clang libssl-dev repo rsync flex curl bison aria2
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            
       - name: Sync recovery source and device tree
         run: |
             mkdir work
             cd work
             repo init -u $MANIFEST --depth=1
             repo sync -c -j4 --force-sync --no-clone-bundle --no-tags
             git clone --depth=1 $DT_LINK $DT_PATH
             
       - name: Build
         run: |
              cd work
              . build/envsetup.sh && lunch omni_$DEVICE-eng && export ALLOW_MISSING_DEPENDENCIES=true && mka $TARGET
             
       - name: Release recovery image
         uses: softprops/action-gh-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tag_name: TWRP_10.0
           name: TWRP-r7
           files: | 
             work/out/target/product/r7/recovery.img
